"""
train_surrogates.py
-------------------
MLOps script: Train three LightGBM surrogate models for the MOIC inventory agent.

Feature schema  : ADI, CV2, R, L, TSL
Target schema   : AvgInventory, LostSales, NumOrders

Data source priority:
  1. Dataset/ml_training_data.csv   (generated by simulation.py — real simulated labels)
  2. Auto-generated synthetic dataset (10,000 rows) if the CSV is missing

Saved models (joblib) — filenames match what inventory_tools.py expects:
  models/lgbm_avg_inventory.joblib
  models/lgbm_lost_sales.joblib
  models/lgbm_num_orders.joblib
"""

import os
import time
from pathlib import Path

import numpy as np
import pandas as pd
import joblib
from lightgbm import LGBMRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error

# ---------------------------------------------------------------------------
# 0.  Paths
# ---------------------------------------------------------------------------
ROOT        = Path(__file__).parent
DATA_FILE   = ROOT / "Dataset" / "ml_training_data.csv"
MODELS_DIR  = ROOT / "models"
MODELS_DIR.mkdir(parents=True, exist_ok=True)

FEATURES  = ["ADI", "CV2", "R", "L", "TSL"]
TARGETS   = ["AvgInventory", "LostSales", "NumOrders"]
OUT_FILES = {
    "AvgInventory": MODELS_DIR / "lgbm_avg_inventory.joblib",
    "LostSales":    MODELS_DIR / "lgbm_lost_sales.joblib",
    "NumOrders":    MODELS_DIR / "lgbm_num_orders.joblib",
}

# ---------------------------------------------------------------------------
# 1.  Load or generate training data
# ---------------------------------------------------------------------------

def generate_synthetic_data(n_rows: int = 50_000, seed: int = 42) -> pd.DataFrame:
    """
    Generate a physics-informed synthetic dataset that approximates the
    (R, s, S) lost-sales simulation outcomes from simulation.py.

    The analytical approximations used here are derived directly from the
    MOIC paper formulas in simulation.py:
      - SS  = Z * sigma_D * sqrt(R + L)
      - s_t = D_hat*(R+L) + SS
      - AvgInventory  ~ S_t / 2  (cycle-stock approximation)
      - LostSales     ~ max(0, demand - S_t) * SIM_DAYS  (excess demand)
      - NumOrders     ~ SIM_DAYS / R
    """
    print(f"[data] ml_training_data.csv not found - generating {n_rows:,} synthetic rows...")
    rng = np.random.default_rng(seed)

    SIM_DAYS = 365

    # ── Feature sampling (matches simulation.py ranges) ─────────────────────
    ADI = rng.uniform(1.0, 15.0, n_rows)          # average inter-demand interval
    CV2 = rng.uniform(0.1, 5.0,  n_rows)          # squared CoV
    R   = rng.integers(1, 31,    n_rows)          # review period [1, 30] days
    L   = rng.integers(1, 31,    n_rows)          # lead time     [1, 30] days
    TSL = rng.uniform(0.90, 0.99, n_rows)         # target service level

    # ── Derived demand statistics (from simulation.py section 3) ────────────
    from scipy.stats import norm
    D_hat   = 1.0 / ADI                           # expected daily demand
    sigma_D = D_hat * np.sqrt(CV2)                # std dev of daily demand
    Z       = norm.ppf(TSL)                        # Z-score

    SS  = Z * sigma_D * np.sqrt(R + L)            # safety stock  (Eq. 6)
    s_t = D_hat * (R + L) + SS                    # reorder point (Eq. 5)
    S_t = D_hat * (R + L) + SS                    # order-up-to   (Eq. 187)

    # ── Target approximations ────────────────────────────────────────────────
    # AvgInventory ≈ half the order-up-to level (cycle stock) + safety stock
    AvgInventory = np.maximum(0.0, S_t / 2.0 + rng.normal(0, sigma_D * 0.1, n_rows))

    # LostSales: demand not covered when inventory < demand
    # Approximation: shortfall = max(0, daily_demand - SS) summed over SIM_DAYS
    daily_shortage = np.maximum(0.0, D_hat - SS / (R + L))
    LostSales = daily_shortage * SIM_DAYS + rng.exponential(0.5, n_rows)

    # NumOrders ≈ SIM_DAYS / R (periodic review)
    NumOrders = (SIM_DAYS / R).astype(float) + rng.normal(0, 0.5, n_rows)
    NumOrders = np.maximum(0.0, NumOrders)

    # Add small noise to avoid perfectly collinear targets
    noise = lambda scale: rng.normal(0, scale, n_rows)
    AvgInventory = np.maximum(0.0, AvgInventory + noise(0.2))
    LostSales    = np.maximum(0.0, LostSales    + noise(0.5))
    NumOrders    = np.maximum(0.0, NumOrders    + noise(0.3))

    return pd.DataFrame({
        "ADI": ADI, "CV2": CV2, "R": R, "L": L, "TSL": TSL,
        "AvgInventory": AvgInventory,
        "LostSales":    LostSales,
        "NumOrders":    NumOrders,
    })


def load_data() -> pd.DataFrame:
    if DATA_FILE.is_file():
        print(f"[data] Loading real simulation data from {DATA_FILE} …")
        df = pd.read_csv(DATA_FILE)
        # Normalise column names to match FEATURES / TARGETS lists
        df.columns = [c.strip() for c in df.columns]
        missing = [c for c in FEATURES + TARGETS if c not in df.columns]
        if missing:
            raise ValueError(
                f"ml_training_data.csv is missing columns: {missing}\n"
                f"Found: {df.columns.tolist()}"
            )
        print(f"[data] Loaded {len(df):,} rows x {len(df.columns)} columns.")
        return df
    else:
        return generate_synthetic_data(n_rows=50_000)


# ---------------------------------------------------------------------------
# 2.  Model factory
# ---------------------------------------------------------------------------

def make_lgbm(target: str) -> LGBMRegressor:
    """Return a tuned LGBMRegressor for the given target."""
    common = dict(
        n_estimators      = 300,
        learning_rate     = 0.05,
        num_leaves        = 63,
        max_depth         = -1,
        min_child_samples = 20,
        subsample         = 0.8,
        colsample_bytree  = 0.8,
        reg_alpha         = 0.1,
        reg_lambda        = 0.1,
        random_state      = 42,
        n_jobs            = -1,
        verbose           = -1,
    )
    # LostSales is heavy-tailed → use Huber / tweedie objective
    if target == "LostSales":
        common["objective"] = "regression_l1"   # MAE objective, more robust to outliers
    return LGBMRegressor(**common)


# ---------------------------------------------------------------------------
# 3.  Train + evaluate + save
# ---------------------------------------------------------------------------

def rmse(y_true, y_pred):
    return float(np.sqrt(mean_squared_error(y_true, y_pred)))


def train_and_save(df: pd.DataFrame):
    X = df[FEATURES]
    X_train, X_test, y_train_all, y_test_all = train_test_split(
        X, df[TARGETS], test_size=0.15, random_state=42
    )

    print(f"\n{'='*60}")
    print(f"  Training set : {len(X_train):,} rows")
    print(f"  Test set     : {len(X_test):,} rows")
    print(f"  Features     : {FEATURES}")
    print(f"{'='*60}\n")

    results = {}
    for target in TARGETS:
        y_train = y_train_all[target]
        y_test  = y_test_all[target]

        model = make_lgbm(target)
        t0 = time.time()
        print(f"[train] Fitting model for target '{target}' …")
        model.fit(
            X_train, y_train,
            eval_set=[(X_test, y_test)],
        )
        elapsed = time.time() - t0

        y_pred = model.predict(X_test)
        mae  = mean_absolute_error(y_test, y_pred)
        rms  = rmse(y_test, y_pred)

        out_path = OUT_FILES[target]
        joblib.dump(model, out_path)

        results[target] = {"MAE": mae, "RMSE": rms, "time_s": elapsed}
        print(f"  [OK] Saved -> {out_path}")
        print(f"    MAE  = {mae:.4f}   RMSE = {rms:.4f}   ({elapsed:.1f}s)\n")

    return results


# ---------------------------------------------------------------------------
# 4.  Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("\n" + "="*60)
    print("  MOIC Surrogate Model Training Script")
    print("="*60 + "\n")
    import sys; sys.stdout.reconfigure(encoding='utf-8', errors='replace') if hasattr(sys.stdout, 'reconfigure') else None

    df = load_data()
    print("\n[data] Target statistics:")
    print(df[TARGETS].describe().round(3).to_string())
    print()

    results = train_and_save(df)

    print("="*60)
    print("  TRAINING SUMMARY")
    print("="*60)
    for target, metrics in results.items():
        print(f"  {target:<20}  MAE={metrics['MAE']:.4f}  RMSE={metrics['RMSE']:.4f}")

    print(f"\n  Models saved to: {MODELS_DIR.resolve()}")
    print("  inventory_tools.py will now load real predictions instead of zeros.")
    print("="*60)
